### ISSUE TITLE
在 `hvml-spec-v1.0-zh.md` 中可能存在语言使用错误

### ISSUE THREAD

**Issue by xqm32** [HVML/hvml-docs#4]
在如下行中，`在未获得版权所有人书面许可之前` 一句是否应当删除 `未` 字，即为 `在获得版权所有人书面许可之前`🤔

https://github.com/HVML/hvml-docs/blob/e7fa420fa5a3ea9dd1ba0154b6eb5ea687ea16f7/zh/hvml-spec-v1.0-zh.md?plain=1#L21

本人非法律专业人士，不当之处还请包涵😢

**Comment by VincentWei** [comment]
有道理！多谢多谢，这就改。:)

**Comment by VincentWei** [comment]
修改成了：

在未获得版权所有人书面许可的情况下，任何人不得...
